from typing import Protocol

from app.domain.entities import Pokemon


class PokeApiPort(Protocol):
    def fetch_pokemon(self, pokemon_id: int) -> Pokemon: ...

    def fetch_pokemon_by_name(self, name: str) -> Pokemon: ...

    def search_pokemon_ids(self, query: str, limit: int = 20, offset: int = 0) -> list[int]: ...

    def fetch_type_chart(self, attack_type: str) -> dict[str, float]: ...

    def list_pokemon_ids(self, limit: int = 20, offset: int = 0) -> list[int]: ...
