from typing import Protocol, Dict, List

from app.domain.entities import BattleContext, LobbyEntry, Pokemon


class CatalogPort(Protocol):
    def list_user_pokemon(self, user_id: int) -> List[Pokemon]: ...

    def get_user_pokemon(self, user_id: int, pokemon_id: int) -> Pokemon | None: ...

    def upsert_user_pokemon(self, user_id: int, pokemon: Pokemon) -> Pokemon: ...

    def set_active(self, user_id: int, pokemon_id: int) -> None: ...

    def get_active(self, user_id: int) -> Pokemon | None: ...

    def set_active_team(self, user_id: int, pokemon_ids: List[int]) -> None: ...

    def get_active_team_ids(self, user_id: int) -> List[int]: ...


class BattleRepoPort(Protocol):
    def create_battle(
        self,
        p1: int,
        p2: int,
        p1_team: List[Pokemon],
        p2_team: List[Pokemon],
        seed: int,
        type_chart: dict[str, dict[str, float]],
        order: List[str],
        initiative: Dict,
    ) -> int: ...

    def load_battle(self, battle_id: int) -> BattleContext: ...

    def save_turn(self, battle_id: int, turn: Dict) -> None: ...

    def update_state(self, battle_id: int, state: Dict) -> None: ...

    def finish(self, battle_id: int, result: Dict) -> None: ...

    def list_battles(self, user_id: int) -> List[Dict]: ...

    def list_events(self, battle_id: int) -> List[Dict]: ...

    def get_replay(self, battle_id: int) -> Dict | None: ...

    def update_pending_actions(self, battle_id: int, pending_actions: Dict[str, Dict | None]) -> None: ...


class LobbyPort(Protocol):
    def enqueue(self, user_id: int, pokemon_ids: List[int]) -> None: ...

    def try_match(self, user_id: int) -> LobbyEntry | None: ...

    def open_code_lobby(self, user_id: int, pokemon_ids: List[int], code: str) -> None: ...

    def try_match_code_lobby(self, user_id: int, code: str) -> LobbyEntry | None: ...

    def close_code_lobby(self, user_id: int, code: str) -> bool: ...
